name: Stylua
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          version: v0.17.1
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
